### PR TITLE
Transactions

### LINKED ISSUE #164: security by default
Enable security by default for ldproxy-manager, ldproxy-styles-manager and ldproxy-transactions.

### LINKED ISSUE #191: Errors creating a new feature
POSTing a new feature creates this exception:

```
! java.lang.ArrayIndexOutOfBoundsException: -1
! at java.util.ArrayList.elementData(ArrayList.java:422)
! at java.util.ArrayList.get(ArrayList.java:435)
! at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
! at de.ii.xtraplatform.feature.provider.sql.app.SchemaBuilderSql.create(SchemaBuilderSql.java:46)
! at de.ii.xtraplatform.feature.provider.sql.app.SchemaBuilderSql.create(SchemaBuilderSql.java:29)
! at de.ii.xtraplatform.features.domain.ReverseSchemaBuilder.visit(ReverseSchemaBuilder.java:24)
! at de.ii.xtraplatform.features.domain.ReverseSchemaBuilder.visit(ReverseSchemaBuilder.java:17)
! at de.ii.xtraplatform.features.domain.SchemaBase.accept(SchemaBase.java:120)
! at de.ii.xtraplatform.features.domain.SchemaBase.lambda$accept$1(SchemaBase.java:121)
! at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
! at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
! at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
! at de.ii.xtraplatform.features.domain.SchemaBase.accept(SchemaBase.java:122)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.__M_writeFeatures(FeatureProviderSql.java:302)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.writeFeatures(FeatureProviderSql.java)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.__M_createFeatures(FeatureProviderSql.java:237)
! at de.ii.xtraplatform.feature.provider.sql.app.FeatureProviderSql.createFeatures(FeatureProviderSql.java)
! at de.ii.ldproxy.wfs3.transactional.CommandHandlerTransactional.postItemsResponse(CommandHandlerTransactional.java:51)
...
```

### PR DESCRIPTION
**Pull request by azahnen**
Closes #164.
Fixes #191.

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele I deployed the daraa and vineyards configurations with transactions enabled here: https://demo-tr.ldproxy.net

You need to authorize in swagger-ui with a token, this one should be valid for some years: `eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJTVVBFUkFETUlOIiwicmVtZW1iZXJNZSI6ZmFsc2UsImV4cCI6MTc3MTU5MTc2OH0.Uw1q_wj9CD6QK3ndCqzjX_YqkV2VlZSenzRJkkffDQ4`
If you want to create tokens yourself, I would have to publish additional endpoints.

If you want to use other clients, you can see in swagger-ui how to set the `Authorize` header.

**Comment by cportele** [comment]
The general behaviour works as expected, but I have noticed the following issues:

* If the payload is invalid JSON, a 500 is returned and a JSON parsing stacktrace is logged. If the payload does not fit the provider schema (e.g., an integer instead of a datetime), a 500 is returned and internally the mapping issue is logged. In both cases, a 400 needs to be returned with appropriate error messages.
* In PUT the `id` member is used, not the `featureId` from the path. E.g., a PUT to `.../items/13` with `id: 12` creates/changes the feature with id 12. The id in the feature should be ignored and the featureId from the path should be used.
* The current logic does not work in cases where the featureId is not the sort id/sequence, e.g., in the Vineyards API. POSTing a new feature with `"id": 999999` results in a 201 response with `location: https://demo-tr.ldproxy.net/vineyards/collections/vineyards/items/1588`, but accessing the URL results in a 404. If I search for the inserted feature using `.../items?name=XXX`, I get the feature in the feature collection, but without an id attribute. Probably the right approach here is to add the property that is mapped to the featureId in the create-schema as a regular property. The check for id collision and the URI that is reported in 201 need to take the provider schema into account.

We also need to update the documentation how to configure the security aspects.

Just so that I do not forget it - the following are todos and should be moved to new issues:

* Implement option to return an error, if PUT tries to create a new feature. This should be the default behaviour (this will be the behaviour specified in Part 4).
* Implement the create/replace/update schemas.
* Add option to validate payload against the schema first.
* Implement PATCH.

**Comment by azahnen** [comment]
@cportele 
- A 400 is now returned for most JSON or SQL errors including the exception message. I still wouldn't deem that production-ready, we would need to "translate" at least the SQL errors.
- PUT should now work as expected.
- vineyards should now work as expected. A possibly unwanted side-effect of PUT for vineyards is that a new `ogc_fid` is generated.

**Review by cportele — APPROVED** [review]
This looks good. I have created #411 for follow-ups.

**Pull request merged**
