### PR TITLE
fix json schema serialization + deserialization

### LINKED ISSUE #659: Fetching style metadata can lead to server errors
### ldproxy Version

master

### Current Behavior

The metadata of a style cannot be accessed, an exception is thrown. At least for cases where the metadata is not derived on-the-fly, but where a metadata resource is on the server. This is a result of a [recent change](https://github.com/interactive-instruments/ldproxy/pull/641#issuecomment-1094943095). The style metadata includes JSON Schemas, so we need to be able to deserialize it. After the removal of the `@JsonTypeInfo` annotations, Jackson no longer knows which subtype to create. 

Note that most deployments will only derive the metadata on the fly, so this will affect only a few deployments (like the Daraa demo API, but we can remove the specific metadata for now).

### Expected Behavior

The style metadata is returned with a 200 response.

### Steps to Reproduce

Access any stored resource `/styles/{id}/metadata` where the resource in the server repository.

### Relevant log output

```shell
Server Error with ID 534fb00ca9fdf0ef: Cannot construct instance of `de.ii.ogcapi.features.core.domain.JsonSchema` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: de.ii.ogcapi.styles.domain.ImmutableStyleMetadata$Json["layers"]->java.util.ArrayList[7]->de.ii.ogcapi.styles.domain.ImmutableStyleLayer$Json["attributes"]->java.util.LinkedHashMap["F_CODE"])
```

### PR DESCRIPTION
**Pull request by azahnen**
### Pull request checklist

-   [x] All checks are passing

### Changes introduced by this PR

Closes #659.

- reverts the changes from #641 
- addresses the original issue by using custom converters for `JsonSchemaTrue` and `JsonSchemaFalse`
- enables deserialization for most subtypes, I am pretty sure it does not work for subtypes without an actual `type`

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-867.surge.sh

**Comment by azahnen** [comment]
Postponed to v3.4, rebased to master.

**Comment by azahnen** [comment]
Deserialization should work for all subtypes before merging.

**Comment by cportele** [comment]
@azahnen 

I have changed the JSON Schema deserialization to a custom converter to also handle the schemas without a `type` property (e.g., `oneOf`, `$ref`, `true`, `false`).

In addition, this fixes two issues in the Styles module that I noticed during testing.

Could you review, if this is ready for merging?

**Pull request merged**
