### PR TITLE
Layer control

### LINKED ISSUE #1015: Improve layer control in webmap
This enhancement will improve controlling the layers that are visible in the MapLibre web map.

The web map uses MapLibre styles. A style has two layer concepts: 

- tile layers: a layer in a vector tile = a feature type / collection in the API;
- style layers: part of a feature style, associated with a tile layer; style layer types are fill, line, symbol, circle, basemap, etc); style layers can be restricted to certain zoom levels and depend on feature attributes.

### Overview

The following capabilities will be implemented:

- Tile layers can be aggregated into layer groups.
- Tile layers can have sublayers that contain a subset of features based on a filter expression. A tile sublayer is associated with exactly one tile layer. Each feature of the tile layer can be in 0..n sublayers, but sublayers are mainly useful, if each feature is in one sublayer.
- Individual tile sublayers, tile layers or layer groups can be enabled or disabled. 
- For the tile layers (if there are no sublayers) or tile sublayers there will be a symbol next to the layer names.
- It will be possible to switch between several basemaps.

### Dialog

The layer selection dialog shows the hierarchy of the layer groups, the tile layers and - if available - the tile sublayers. The style layers are only present in the style and are not known as such to the user. The dialog should look similar to the layer widget in QGIS:

QGIS

### Layer symbol

The symbol next to a tile layer without sublayer or next to a tile sublayer must represent the features in the layer. For this purpose, a certain zoom level and/or certain attributes may have to be used for the visualization. In these cases, these must be specified for the layer/sublayer. 

Depending on the style layers associated with the tile layer/sublayer, this may not result in a satisfactory visualization. These cases would have to be dealt with at a later stage.

For symbol generation the idea is to use the library [watergis/legend-symbol](https://github.com/watergis/legend-symbol), which simply delegates the evaluation of expressions to [mapbox/mapbox-gl-style-spec](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec). This library doesn't currently support all the capabilities we need, but it should be fairly easy to extend in a fork.

### Associating tile layers/sublayers with style layers

When turning a layer/sublayer on/off in the dialog, the associated features have to be shown/hidden in the map. 

In the case of a tile layer, this is easy. The visibility for all style layers for this tile layer (the `source-layer` member) is set to 'visible' or 'none'. 

In the case of a tile sublayer, the associated style layers have to be configured in the style metadata. Sublayers must be organized so that a style layer is assigned to exactly one tile sublayer.

Note: Another option would be not to turn on/off the visibility of the style layers, but to dynamically adjust the filter in the style layer to show/hide the selected features. The problem with this is that the filter in the "all selected" state must always be preserved and it will hardly be possible to adjust the filters in a stable way when there are multiple sublayers with similar filters.

### Layer configuration

The tile layers and the style layers are already specified in the style. The information about layer groups and tile sublayers will be included in the style metadata object. The information about the zoom level and feature properties to use for the symbol are also included in the style metadata.

Here is an example of how the metadata might look like. The details of the JSON syntax can change in the implementation.

```json
{
  "version": 8,
  "id": "group-example",
  "metadata": {
    "ldproxy:layers": [
      { 
        "id": "Basemap",
        "type": "group",
        "isBasemap": true,
        "entries": [ 
          {
            "id": "basemap.de Grau",
            "type": "source-layer"
          }, {
            "id": "basemap.de Farbig",
            "type": "source-layer"
          }, {
            "id": "Orthofotos",
            "type": "source-layer"
          }
        ] 
      },
      { 
        "id": "Planfeststellung",
        "type": "group",
        "entries": [ 
          {
            "id": "PFS_Plan",
            "type": "source-layer"
            "$comment": "Hier sind keine Sonderregeln erforderlich"
          }, {
            "id": "PFS_Stationierungslinie",
            "type": "source-layer"
          }, {
            "id": "PFS_Trassenkorridor",
            "type": "source-layer",
            "sub-layers": [ 
              {
                "id": "festgelegt",
                "layers": ["pfs_trassenkorridor_fill"],
              }, {
                "id": "Rückbau",
                "layers": ["pfs_trassenkorridor_rueckbau_line"],
                "properties": {
                  "art": "4000"
                }
              }
            ]
          }, 
          ... 
        ] 
      },
      { 
        "id": "Bestandsnetze",
        "entries": [ 
          {
            "id": "BST_Stromleitung",
            "type": "source-layer",
            "sub-layers": [ 
              {
                "id": "Höchstspannung 380 kV",
                "layers": ["bst_stromleitung_line_380kv"],
                "properties": {
                  "spannung": "30003"
                }
              }, {
                "id": "Höchstspannung 220 kV",
                "layers": ["bst_stromleitung_line_220kv"],
                "properties": {
                  "spannung": "30002"
                }
              }, {
                "id": "Hochspannung 110 kV",
                "layers": ["bst_stromleitung_line_110kv"],
                "zoom": 11,
                "properties": {
                  "spannung": "30001"
                }
              }, {
                "id": "Rückbau 380 kV",
                "layers": ["bst_stromleitung_line_rückbau_380kv"],
                "properties": {
                  "status": "2000",
                  "spannung": "30003"
                }
              }, {
                "id": "Rückbau 220 kV",
                "layers": ["bst_stromleitung_line_rückbau_220kv"],
                "properties": {
                  "status": "2000",
                  "spannung": "30002"
                }
              }, {
                "id": "Rückbau 110 kV",
                "layers": ["bst_stromleitung_line_rückbau_110kv"],
                "zoom": 11,
                "properties": {
                  "status": "2000",
                  "spannung": "30001"
                }
              } 
            ]
          }, {
            "id": "BST_Umspannanlage",
            "type": "source-layer"
          },
          ... 
        ] 
      } 
    ]
  },
  "sources": [
    ...
  ],
  "layers": [
    ...
  ]
}
```

### Basemap layers

Only one basemap layer should be enabled at any time. If a layer group is marked as a group of basemap layers, a radio button is used, not a check box.

### Default

If no information is included in the style metadata, the will be no layer groups and no sublayers. That is, there will be one entry for each tile layer. The symbol will be generated for a feature without properties at some fixed zoom level.

### API configuration

Layer selection in the web map will be enabled via the `webmapWithLayerControl` option in the STYLES building block (as it is now). The new dialog will replace the previous layer selection implementation.

### PR DESCRIPTION
**Pull request by PZahnen**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [ ] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

Closes #1015 .

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele 
This is ready for review. It has to be enabled with `webmapWithLayerControl: true`. The plugin first checks for a configuration in the style metadata, if none is found it uses the configuration passed by ldproxy.
I will add some proposals regarding the configuration syntax to #1015.

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-1018.surge.sh

**Comment by cportele** [comment]
@azahnen - I did an initial test with the vineyards API and have run into issues:

The default configuration seems to be that each style layer is converted into a sublayer. The default should be one entry for each source-layer (in the vineyards case, just the "vineyards" layer):

> If no information is included in the style metadata, the will be no layer groups and no sublayers. That is, there will be one entry for each tile layer. The symbol will be generated for a feature without properties at some fixed zoom level.

I then tried to configure the default explicitly:

```json
{
  "ldproxy:layers": [
    {
      "id": "vineyards",
      "type": "source-layer"
    }
  ]
}
```

This resulted in this layer control:

Bildschirmfoto 2023-08-02 um 12 33 16

De-selecting the entry did not change the visibility of the three style layers of the tile/source layer as it should:

> When turning a layer/sublayer on/off in the dialog, the associated features have to be shown/hidden in the map.
> 
> In the case of a tile layer, this is easy. The visibility for all style layers for this tile layer (the source-layer member) is set to 'visible' or 'none'.

There is also no symbol shown for the entry. Symbols only seem to be shown for sublayers?

> For the tile layers (if there are no sublayers) [...] there will be a symbol next to the layer names.











As a first test I tried the standard case (no sublayers). 

```json
{
    "ldproxy:layers": [
      {
        "id": "vineyards",
        "type": "source-layer"
      }
    ]
}
```

**Comment by cportele** [comment]
I did more tests. In general, this looks good, except the issue noted in the previous comment and the following issues:

- In the `strassen` API, the layer control is not shown. Exceptions are logged in the developer console ("TypeError: Cannot read properties of null (reading 'attributes')").
- When I open the layer control, the following is logged in the developer console ("GET http://localhost:7080/rest/services/vineyards/styles/null 404 (Not Found)").
- I was not able to get the basemap / radio button group to work. The radio buttons have no effect with the group configuration below (based on the description in the issue; however, "source-layer" does not really make sense for a raster layer, but we will discuss the JSON anyhow). 
 
```json
{
  "id": "Basemap",
  "type": "group",
  "isBasemap": true,
  "entries": [
    {"id": "Grau"  , "type": "source-layer"},
    {"id": "Farbig", "type": "source-layer"}
  ]
}
```

**Comment by azahnen** [comment]
@cportele The issues should be fixed. For `strassen` I guess the icon library tries to render something for the symbol layer which does not work. It now shows the default `T`, I will have another look if it tries to render something more like the actual symbols.

**Comment by cportele** [comment]
@azahnen - Excellent, tests are looking very good so far.

**Review by cportele — APPROVED** [review]
Looks good now. Tested also `onlyLegend` and `opened`.

I only noticed one "issue". For symbol layers that are not text, but really a symbol (from a sprite or a single unicode character) it would be nice, if this would be shown instead of the `T`. But I guess for symbol layers the library does not support rendering an icon from the sprite or use a text that is not "T"? In that case we should leave it as it is for now.

Here is the daraa layer control from my tests:

Bildschirmfoto 2023-08-04 um 14 03 08

**Comment by azahnen** [comment]
@cportele The lib has support for icon images, but from looking at the code it does not work as documented by just passing the sprite URL from the style. We would have to load the json and png files ourselves and pass them to the lib, there does not seem to be way to get them from maplibre.

I am actually a bit surprised about the circle your icon shows for `utilityinfrastructurepnt`. First, that seems to match the icon rendered in the map, second, I get a `T` in the legend instead and third, the rendering in the map seems to be wrong, `pylon_wilson_b` looks more like the Eiffel Tower.

**Comment by cportele** [comment]
OK, I think we then leave it as it is.

The circle for `utilityinfrastructurepnt` is the result of testing also a `circle` layer. Sorry, I should have mentioned that.

**Comment by cportele** [comment]
The `pylon_wilson_b` could also be an error in the sprite. `pylon_b` is the Eiffel tower, `pylon_wilson_b` is the circle next to it.

**Comment by azahnen** [comment]
@cportele Ok, that explains it. I added sprite loading, please test again.

**Comment by cportele** [comment]
@azahnen - Very good, works well in my tests! I think this can be merged now (but we need a follow-up issue to document the `ldproxy:layerControl` syntax).

**Pull request merged**
