### PR TITLE
build improvements

### LINKED ISSUE #1116: remove the manager
This will completely remove the Manager from the software. The Manager has not been maintained for a while and will be discontinued. 

It will be superseded by the [Editor](https://docs.ldproxy.net/editor/).

### PR DESCRIPTION
**Pull request by azahnen**
### Changes introduced by this PR

- closes #1116 
- removes special IntelliJ modules
- makes all xtraplatform/ogcapi dependencies explicit
- skip docs generation for run task
- upgrade to Gradle 8.5
- upgrade to Woodpecker 2.0
- define all third party library versions in central catalog (preparation for dependabot)
- preparation for maintenance levels (see `./gradlew modules`)

Depends on interactive-instruments/xtraplatform#156
Depends on interactive-instruments/xtraplatform-spatial#246

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele 
Please check if everything still works in your environment. You have to run `./gradlew clean` in all three repos, in `xtraplatform` also `rm -r xtraplatform-core xtraplatform-dev xtraplatform-gradle-plugins`.

**Review by cportele — APPROVED** [review]
It works in my environment. 

In addition, I had to delete ldproxy-manager in ldproxy.

**Comment by cportele** [comment]
@azahnen 

I now get errors when I try to commit a change in ldproxy:

```
...
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ogcapi-stable:ogcapi-foundation:compileJava'.
> javax.annotation.processing.FilerException: Attempt to recreate a file for type de.ii.ogcapi.foundation.app.OgcApiFactory_OgcApiFactoryAssisted_Impl

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ldproxy-product:compileJava'.
> javax.annotation.processing.FilerException: Attempt to recreate a file for type de.ii.ldproxy.product.domain.AutoBindings_CreateFactory
```

Any idea why this happens?

**Comment by azahnen** [comment]
@cportele That happens every now and then, even before the changes from this PR. Try a `./gradlew clean check`.

**Pull request merged**
