### PR TITLE
Tile caches

### LINKED ISSUE #735: add tile staging cache
An operational tile cache should be considered immutable. That means a re-seeding has to work on a staging cache that is promoted to be the new operational cache when done.

### PR DESCRIPTION
**Pull request by azahnen**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [ ] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

Closes #735.

Moves tile providers to `xtraplatform-spatial`, see interactive-instruments/xtraplatform-spatial#162.

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-811.surge.sh

**Comment by cportele** [comment]
@azahnen - I am testing the PR, but I am running into problems testing it in the IDE (I noticed some issues with seeding too many tiles when testing with the docker image that I need to debug). I am getting errors "Could not initialize class org.kortforsyningen.proj.Units". Is this a known issue or do you have any idea how to fix this?

**Comment by azahnen** [comment]
@cportele I am merging some changes to the proj loader right now. When that is done, you need to merge the master branch into tiles. Then it should work again.

**Comment by cportele** [comment]
@azahnen - OK, thanks. Let me know, when the proj updates are ready to be merged and I can continue testing.

**Comment by azahnen** [comment]
@cportele I already merged the changes into the two tiles branches and had to fix some resulting issues, it should work again.

**Review by cportele — APPROVED** [review]
LGTM

See https://github.com/interactive-instruments/xtraplatform-spatial/pull/162 and https://github.com/interactive-instruments/xtraplatform/pull/115

**Comment by azahnen** [comment]
@cportele Yes, that is a bug. A second cache should be created, but it is not. I will push a fix before merging.

**Pull request merged**
