### PR TITLE
Arm64

### LINKED ISSUE #693: support docker platform linux/arm64
Create multi-platform docker images, supporting both `linux/amd64` and `linux/arm64`.

### PR DESCRIPTION
**Pull request by azahnen**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [ ] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

Closes #693.

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-694.surge.sh

**Comment by azahnen** [comment]
@cportele This should automatically build and run the arm64 image in your development environment.

**Review by cportele — APPROVED** [review]
Yes, it does! 🚀

**Comment by azahnen** [comment]
@cportele The docker image is now multi-platform: https://hub.docker.com/r/iide/ldproxy/tags?page=1&name=next
The same is true for the images in the internal registry.

**Comment by cportele** [comment]
@azahnen - very good, the speed of the arm64 variant feels much faster on my machine than the amd64 variant.

**Pull request merged**
