### PR TITLE
fix transactions

### PR DESCRIPTION
**Pull request by azahnen**

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele I tested this with zoomstack and daraa.

**Comment by cportele** [comment]
@azahnen - I have tested it:

* It works for flat table features with no joins that use the primary integer key as the ID.
* For other IDs, PUT and DELETE result in SQL errors. Multiple POSTs create multiple features with the same ID.
* Features with joins result in SQL errors.

I will run a few more tests tomorrow. Maybe we should also add validation checks that disable the module, if the preconditions are not met for a collection?

**Comment by azahnen** [comment]
> * It works for flat table features with no joins that use the primary integer key as the ID.
> * For other IDs, PUT and DELETE result in SQL errors. Multiple POSTs create multiple features with the same ID.

We only ever supported auto-incrementing primary keys, which are integers by nature.

> I will run a few more tests tomorrow. Maybe we should also add validation checks that disable the module, if the preconditions are not met for a collection?

Yes, that should be part of `typesValidation`, which would then set `provider.supportsTransactions` to disabled, which can then be handled in the transactions module. But that would be future work.

**Comment by cportele** [comment]
I have added the follow-ups to #411.

**Review by cportele — APPROVED** [review]

**Pull request merged**
