### PR TITLE
improve "result-type" parameter

### LINKED ISSUE #706: Support for hitsOnly
### ldproxy Version

master

### Current Behavior

Originally the API supported a request to not return the features, but just the number of features that would be returned. The `hitsOnly` option is still in `FeatureQuery` and the `TransformationContext` classes, but support for it was removed at some point in the overhaul of the transformation pipeline implementation. Such a capability is currently not supported by OGC API Features, but may still be helpful. The capability should at least be restored, even if it is not available via the API at this point. It can also be useful internally.

There are also the options `propertyOnly` and `onlyHitsIfMore` (the latter only in `TransformationContext`), which also have no effect. If these are no longer needed, they should be removed.

### Expected Behavior

`hitsOnly` is supported again.

### Steps to Reproduce

Execute a query internally with `hitsOnly` set to `true`. The setting has no effect.

### Relevant log output

```shell
n/a
```

### PR DESCRIPTION
**Pull request by cportele**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [x] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

Closes #706

Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/281

One comment for discussion: "result-type" is not specified in the OGC API specs, but it has always been in FEATURES_CORE. Should this parameter be moved to its own module in ogcapi-custom?

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-1253.surge.sh

**Review by azahnen — APPROVED** [review]
LGTM. I guess we put it into FEATURES_CORE since we expected it to be included in the spec someday. If that will not happen in the foreseeable future, I think we should move it to ogcapi-custom.

**Comment by cportele** [comment]
@azahnen - Since there is no active discussion at the moment, I have moved the query parameter to a new RESULT_TYPE building block in ogcapi-custom.

**Comment by cportele** [comment]
@azahnen - the CI build fails with a vuepress error, but I do not see what the issue is and locally I do not get an error. Do you have an idea, what goes wrong?

**Comment by azahnen** [comment]
@cportele The issue was in the `labelTemplate` docs. For some reason pipes have to be escaped like this `\|`, an example is also in the `stringFormat` docs. The build was successful now.

**Comment by cportele** [comment]
@azahnen - Thanks!

**Pull request merged**
