### PR TITLE
Add/migrate unit tests

### PR DESCRIPTION
**Pull request by bekakh**

### CODE REVIEW

**Comment by azahnen** [comment]
@bekakh @cportele I upgraded json-schema-validator, can one of you check if it is working?

**Comment by cportele** [comment]
Thanks @azahnen. @bekakh, can you check, if this works in your tests? I will check it later, too.

**Comment by bekakh** [comment]
@cportele @azahnen I'm still getting the same error, will push a simple test shortly.

**Comment by cportele** [comment]
@bekakh 
There are two issues with the validation:

* The validator API has changed between 1.0.24 and 1.0.48. We need to explicitly identify the schema version when creating the schema factory. Otherwise it is draft 04.
* The validation also fails, because the validator cannot handle mixed schema versions and the feature schema uses draft 2019-09 and the referenced GeoJSON schemas use draft 07.

The first issue is easy to fix. The second requires the use of GeoJSON schemas according to 2019-09. I will work on an update.

In addition, the expected result should be `result.isEmpty()`, if the instance is valid against the schema. If it is invalid, the result should be `result.isPresent()` and the value is the error message.

**Comment by cportele** [comment]
@bekakh - I have updated the code and the initial tests. Please continue to add the other test cases.

What is open is that we avoid generating 2019-09 schemas that reference 07 schemas from GeoJSON, but this is separate and does not impact the tests. I will take care of that.

**Comment by bekakh** [comment]
@cportele thanks, working on it.

**Comment by azahnen** [comment]
@bekakh I reviewed the migrated GeoJSON tests, looks good so far. To finish the migration, could you

- [ ] also migrate the empty tests like `GeoJsonWriterIdSpec` as pending tests (and if you have any idea how to implement the tests, please do so)
- [ ] also migrate `FeatureTransformerGeoJsonTest` (I pushed a fix, so the old TestNG test would pass now)
- [ ] when you are done, just remove the `src/test/java` directory

**Comment by cportele** [comment]
@bekakh - I looked at the schema generation tests for features (OpenAPI and JSON Schema). This looks good, but we should extend the tests to cover all aspects that we can express in a FeatureSchema (all SchemaBase.Type values and the constraints, too). If it helps I could check which of the feature schemas from existing API configurations we could use as a starting point.

**Comment by bekakh** [comment]
@cportele yes, that would be useful.

**Comment by cportele** [comment]
@bekakh - I have compiled this one and made it more generic:

```yaml
type: OBJECT
label: foo
description: bar
properties:
  id:
    type: INTEGER
    role: ID
    label: foo
    description: bar
  string:
    type: STRING
    label: foo
    description: bar
    constraints:
      required: true
  link:
    type: OBJECT
    objectType: Link
    label: foo
    description: bar
    properties:
      title:
        type: STRING
        label: foo
        description: bar
      href:
        type: STRING
        label: foo
        description: bar
  links:
    type: OBJECT_ARRAY
    objectType: Link
    label: foo
    description: bar
    constraints:
      minOccurrence: 1
      maxOccurrence: 5
    properties:
      title:
        type: STRING
        label: foo
        description: bar
      href:
        type: STRING
        label: foo
        description: bar
  geometry:
    type: GEOMETRY
    geometryType: MULTI_POLYGON
    label: foo
    description: bar
  datetime:
    type: DATETIME
    label: foo
    description: bar
  endLifespanVersion:
    type: DATETIME
    label: foo
    description: bar
  boolean:
    type: BOOLEAN
    label: foo
    description: bar
  percent:
    type: FLOAT
    label: foo
    description: bar
    constraints:
      min: 0
      max: 100
  strings:
    type: VALUE_ARRAY
    valueType: STRING
    label: foo
    description: bar
  objects:
    type: OBJECT_ARRAY
    objectType: Object1
    label: foo
    description: bar
    properties:
      integer:
        type: INTEGER
        label: foo
        description: bar
      date:
        type: DATETIME
      object2:
        type: OBJECT
        objectType: Object2
        properties:
          regex:
            type: STRING
            constraints:
              regex: '^_\\w+$'
          codelist:
            type: STRING
            constraints:
              codelist: mycodelist
          enum:
            type: STRING
            constraints:
              enum:
              - foo
              - bar
          strings:
            type: VALLUE_ARRAY
            valueType: STRING
```

**Review by azahnen — APPROVED** [review]
The GeoJSON part looks fine.

If I find the time I will also look into the schema generator tests.

**Review by cportele — APPROVED** [review]
I reviewed the schema tests and made some minor additions. I have also merged the latest master changes into the branch and updated the tests / added schema tests for draft-7.

The ogcapi-stable tests are now successful.

**Comment by azahnen** [comment]
@cportele I reviewed the schema generation part, looks good to me. Can I merge this or are you not done yet?

**Comment by cportele** [comment]
@azahnen - Yes, please merge this PR

**Pull request merged**
