### PR TITLE
gpkg

### PR DESCRIPTION
**Pull request by azahnen**
Closes interactive-instruments/ldproxy-project-management#102.

Sample configuration: https://gitea.ci.interactive-instruments.de/ldproxy/gpkg
Sample deployment: https://gpkg.ldproxy.net

@cportele 
- This will not work out of the box in your dev env as `libspatialite` for macOS is not included. It should work if you install it as a system library (`brew install sqlite3 libspatialite`).
- I enabled [git-lfs](https://git-lfs.github.com) in Gitea and used it for the `gpkg` file in the repo. This means you need to install [git-lfs](https://git-lfs.github.com) locally if you do not already have it to be able to clone the repo including the `gpkg` file. We should then use git-lfs for all data dumps in the repos from now on.

### CODE REVIEW

**Comment by cportele** [comment]
The libs were already installed, but I have upgraded them to the latest version. I do get 

> GeoPackage/Spatialite is not supported for OS 'Mac OS X-x86_64'. It might work if you install libspatialite as a system library.
> ...
> [SQLITE_ERROR] SQL error or missing database (dlopen(/Users/portele/Documents/GitHub/ii/ldproxy/build/data/tmp/mod_spatialite.dylib, 10): image not found)

which I guess is normal, since the version of sqlite3 on a Mac that is invoked by default is part of the OS and does not allow extensions AFAIK. I can open and read a GPKG with the libs that have been installed with brew, but these are not the ones that ldproxy is using. I need to do more research here how/if I can get around the constraints. Stay tuned...

**Comment by cportele** [comment]
Since the error message indicates that the lib is expected to be in the tmp folder, I tried copying it to that location, but that only triggered a fatal error in the JRE when accessing the lib.

**Comment by azahnen** [comment]
@cportele Of course the extension has to be loaded without path when using system libraries, I fixed that. Please try again.

**Comment by cportele** [comment]
@azahnen - No change, same fatal error as with loading a copy of the lib in `tmp`. It happens during the initialization of mod_spatialite in a callback to sqlite3 to register the spatialite SQL functions. 

For testing purposes I also tried to use the same approach as for linux and explicitly copy + load all the libs. Same result.

I will look at this again next week.

```
Current thread (0x00007fb41a598000):  JavaThread "startup" daemon [_thread_in_native, id=82435, stack(0x0000700009dbc000,0x0000700009ebc000)]

Stack: [0x0000700009dbc000,0x0000700009ebc000],  sp=0x0000700009eb69a0,  free space=1002k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsqlite3.dylib+0xccab2]  checkMutexEnter+0x12
C  [libsqlite3.dylib+0xb7a14]  createFunctionApi+0x94
C  [libsqlite3.dylib+0xbdef1]  sqlite3_rtree_geometry_callback+0x81
C  [mod_spatialite.7.dylib+0x82d8b]  register_spatialite_sql_functions+0x7ed8
C  [mod_spatialite.7.dylib+0xd2d30]  sqlite3_modspatialite_init+0x4b
C  [sqlite-3.34.0-ba64dbf4-0bfc-401c-9d89-80379ebd2c98-libsqlitejdbc.jnilib+0x10951]  Java_org_sqlite_core_NativeDB_set_1commit_1listener+0xced7
C  [sqlite-3.34.0-ba64dbf4-0bfc-401c-9d89-80379ebd2c98-libsqlitejdbc.jnilib+0x63af0]  Java_org_sqlite_core_NativeDB_set_1commit_1listener+0x60076
C  [sqlite-3.34.0-ba64dbf4-0bfc-401c-9d89-80379ebd2c98-libsqlitejdbc.jnilib+0xbb993]  Java_org_sqlite_core_NativeDB_set_1commit_1listener+0xb7f19
C  [sqlite-3.34.0-ba64dbf4-0bfc-401c-9d89-80379ebd2c98-libsqlitejdbc.jnilib+0xc0db]  Java_org_sqlite_core_NativeDB_set_1commit_1listener+0x8661
j  org.sqlite.core.NativeDB.step(J)I+0
j  org.sqlite.core.DB.execute(Lorg/sqlite/core/CoreStatement;[Ljava/lang/Object;)Z+108
j  org.sqlite.core.CoreStatement.exec()Z+50
j  org.sqlite.jdbc3.JDBC3Statement.execute(Ljava/lang/String;)Z+45
j  de.ii.xtraplatform.feature.provider.sql.infra.db.SpatialiteDataSource.getConnection(Ljava/lang/String;Ljava/lang/String;)Lorg/sqlite/SQLiteConnection;+64
...
```

**Comment by cportele** [comment]
Since it doesn't yet work in my dev environment I did a test with the docker image of the gpkg branch. I used the Zoomstack GPKG and tested it with auto mode and a fully configured provider/service config. Both worked as expected.

I also did a quick, unscientific performance comparison. Here is a request of a million point features without any joins from the GPKG (duration: 126s):  

```
% curl "http://localhost:7080/rest/services/zoomstack2/collections/names/items?f=json&limit=1000000" > names2.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.8M    0 99.8M    0     0   808k      0 --:--:--  0:02:06 --:--:--  647k
```

The same request to the same API configuration, also running in docker, but with a PGIS backend (duration: 105s):

```
% curl "http://localhost:7080/rest/services/zoomstack/collections/names/items?f=json&limit=1000000" > names.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.8M    0 99.8M    0     0   967k      0 --:--:--  0:01:45 --:--:--  921k
```

The same request to the same API configuration and with a PGIS backend, but running in my local IDE (duration: 34s):

```
% curl "http://localhost:7080/rest/services/zoomstack/collections/names/items?f=json&limit=1000000" > names.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.8M    0 99.8M    0     0  2990k      0 --:--:--  0:00:34 --:--:-- 3200k
```

Just for comparison, here is the same request to the same API configuration with the PGIS backend and in my local IDE, but with a Flatgeobuf output (duration: 11s):

```
% curl "http://localhost:7080/rest/services/zoomstack/collections/names/items?f=fgb&limit=1000000" > names.fgb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72.6M    0 72.6M    0     0  6467k      0 --:--:--  0:00:11 --:--:-- 10.8M
```

**Review by cportele — APPROVED** [review]
On linux everything was working as expected. Let's discuss next week if we see an easy way to support also macOS, too, otherwise we could also declare this a linux-only capability for know.

**Pull request merged**
