### PR TITLE
redesign tiles

### PR DESCRIPTION
**Pull request by azahnen**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [ ] Updated documentation
-   [ ] All checks are passing

### Changes introduced by this PR

- introduces an abstraction layer for tile providers and encapsulates all related functionality
- mostly decouples ogcapi-tiles from ogcapi-features-core
- prepares support of tile provider entities

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele You might start testing `type: FEATURES`, `cache: FILES` and seeding. I am still working on `MBTILES` and `TILESERVER`.

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-786.surge.sh

**Comment by cportele** [comment]
@azahnen - I have started testing and it is looking good so far. I had to make some changes (and while I was at it I already started to address some gaps to v1.0) in branch ["redesign-tiles-t1"](https://github.com/interactive-instruments/ldproxy/tree/redesign-tiles-t1).

**Comment by azahnen** [comment]
@cportele MbTiles Cache and Provider are ready for testing.

**Comment by azahnen** [comment]
@cportele TileServer is ready as well.

**Review by cportele — APPROVED** [review]
I have tested mostly with the demo and lika configurations:

* Provider: FEATURES and MBTILES (configured in TilesConfiguration)
* Cache: FILES and MBTILES
* with various tile matrix sets
* Some issues and improvements were made in a separate branch that should be merged first, see #798

I have not yet tested TileServer / HTTP provider, but we can also do this after merging. There are also still quite a number of TODOs that need to be resolved in the next steps.

**Pull request merged**
