### PR TITLE
text search module

### LINKED ISSUE #713: Move q parameter to its own module
Currently the "q" parameter (text search) is part of Features Core, but should be its own module (ogcapi-text-search in ogcapi-draft).

* Create new module classes TextSearchConfiguration, TextSearchBuildingBlock, and JacksonSubTypeIdsTextSearch  as well as package-info.java
  * add `List<String> getProperties()` to TextSearchConfiguration
  * add derived method that first checks for `getQueryables().getQ()` in FeaturesCoreConfiguration to support existing configurations
* Create new class PathParameterCollectionIdTextSearch matching path "/collections/{collectionId}/items"
* QueryParameterQ
  * move to new module
  * change buildingBlockConfigurationType to TextSearchConfiguration
* FeaturesCollectionQueryables
  * mark `getQ()` as deprecated with version 3.3.0
* FeaturesQueryImpl
  * move the handling of PARAMETER_Q to an extension in the new module to remove any dependency of Features Core from the q parameter; maybe this could be added to QueryParameterQ in `transformParameters()` or `transformQuery()` methods

### PR DESCRIPTION
**Pull request by CabukEge**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [x] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

Closes #713 .

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-723.surge.sh

**Comment by azahnen** [comment]
@CabukEge I made some changes to solve the remaining issues. 

It should work as expected if you override `transformQuery`, move the body of `transformParameters` to `transformQuery` and then add the `Cql2Expression` to the builder with `queryBuilder.addFilters`.

When that is done you can remove `transformParameters`, `getFilterParameters` and the `Cql` member variable.

**Comment by CabukEge** [comment]
@azahnen and @cportele changes completed. The basic functionality works, so it should be checked.

**Review by azahnen — APPROVED** [review]

**Comment by azahnen** [comment]
@cportele 
This can be merged from my point of view:
- it is backwards compatible, i.e. if `queryables.q` is non-empty the module is enabled automatically, and the considered properties are the union of `queryables.q` and the new modules `properties`
-  if `queryables.q` is empty, it has to be enabled explicitly, it is disabled by default
- combining `q` with various other filters works as expected (tested with https://demo.ldproxy.net/zoomstack/collections/names/items?q=NATIONAL&name1=%2ADISTRICT%2A&filter=name2=%27%27&bbox=-9.2230%2C49.8212%2C2.6873%2C60.7782)

Do you want to review this as well or should I merge it?

**Comment by cportele** [comment]
@azahnen - Please merge it. I will not be able to review in the next days and so we should merge it. I will do some tests later before the next release when I migrate some configurations to the new building block. If that brings up issues, we can address them in that process.

**Pull request merged**
