### PR TITLE
Align Tiles and Styles implementation with latest draft, OGC Code Sprint May 2021

### LINKED ISSUE #440: Align Styles implementation with latest draft
https://docs.ogc.org/DRAFTS/20-009.html

- [x] support Styles resources also at `/collections/{collectionId}/styles`
- [x] for styles that include a Mapbox Style at `/styles/{id}`, derive a style with all the other collections removed at `/collections/{collectionId}/styles/{id}`, if no explicit style with that id exists in the Styles resource of the collection
- [x] remove Styles-Info module
- [x] use PUT only for replacing a stylesheet, not for creating a new style
- [x] support `Prefer` header preference "handling" and `dry-run` query parameter instead of the `validation` query parameter

### PR DESCRIPTION
**Pull request by cportele**
Styles:
- support Styles resources also at /collections/{collectionId}/styles
- for styles that include a Mapbox Style at /styles/{id}, derive a style with all the other collections removed at /collections/{collectionId}/styles/{id}, if no explicit style with that id exists in the Styles resource of the collection
- remove styles-info module
- remove conformance class declaration from resources / resources-manager (no longer specified in OGC API Styles)
- use PUT only for replacing a stylesheet, not for creating a new style
- support Prefer header preference "handling" and dry-run query parameter instead of the validation query parameter
- support LYR and QML as style encodings
- improved xsd validation of SLD 1.0 stylesheets
- general improvements

Tiles:
- added support for mbtiles as a feature provider
- support MBTiles as tile cache (one file per tile set)
- in MBTiles caches, empty MVT tiles are represented by a single BLOB
- add capability to purge tiles from the tile cache (by collection, bbox and/or tile matrix set)
- added ETRS89/UTM32N tiling schemes
- update Tile Matrix Set encoding to the latest TMS draft
- add Tileset metadata encoding from the latest TMS draft
- update Tilesets and Tileset resources to the latest OGC API Tiles draft
- update link relation types to the latest OGC API Tiles draft
- includes changes agreed during the code sprint (drafts will be updated)
- refactor MVT transformer, geometry processing in separate classes
- use new JTS capabilities (OverlayNG)
- additional logging during MVT tile processing
- cleanup

General:
- support getSchema(apiData) for sub-collection query parameters for cases where the `{collectionId}` template is used in the API definition

Todo:
- The capability to purge tiles from the tile cache needs testing (and tests)
- The unit tests are outdated and need an update

### CODE REVIEW

**Comment by cportele** [comment]
Reverted the last two commits and moved them to a separate branch [tile-cache](https://github.com/interactive-instruments/ldproxy/tree/tile-cache).

Those commits work on my machine, but in the portainer deployment they result in osgi errors:

```
INFO  [2021-07-05 07:22:16,912]                          - Starting ldproxy 3.0.0-SNAPSHOT  
ERROR: Bundle de.interactive_instruments.ogcapi-tiles [39] Error starting reference:file:/ldproxy/bundles/ogcapi-tiles-3.0.0-SNAPSHOT.jar (org.osgi.framework.BundleException: Unable to resolve de.interactive_instruments.ogcapi-tiles [39](R 39.0): missing requirement [de.interactive_instruments.ogcapi-tiles [39](R 39.0)] osgi.wiring.package; (osgi.wiring.package=jdk.jshell.spi) Unresolved requirements: [[de.interactive_instruments.ogcapi-tiles [39](R 39.0)] osgi.wiring.package; (osgi.wiring.package=jdk.jshell.spi)])
org.osgi.framework.BundleException: Unable to resolve de.interactive_instruments.ogcapi-tiles [39](R 39.0): missing requirement [de.interactive_instruments.ogcapi-tiles [39](R 39.0)] osgi.wiring.package; (osgi.wiring.package=jdk.jshell.spi) Unresolved requirements: [[de.interactive_instruments.ogcapi-tiles [39](R 39.0)] osgi.wiring.package; (osgi.wiring.package=jdk.jshell.spi)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Unknown Source)
INFO  [2021-07-05 07:22:27,458]                          - Store mode: READ_ONLY  
INFO  [2021-07-05 07:22:27,459]                          - Store location: /ldproxy/data/store  
INFO  [2021-07-05 07:22:31,747]                          - Started web server at https://demo.ldproxy.net  
```

**Review by azahnen — APPROVED** [review]
I think a thorough review of this changes would take at least the week, so I just tried to make sure there are no obvious issues:

- I glanced over the code 
- I compiled and ran the branch in my environment
- I made some tests with demo/vineyards to check if existing configurations still work as expected

**Comment by azahnen** [comment]
@cportele The osgi issue occurred because you used `jdk.jshell.spi.ExecutionControl.NotImplementedException` in `StaticTileProviderStoreImpl`. JShell is an interactive learning tool for java and like the package name suggests it is only contained in the JDK, not in the JRE that is used by docker deployments.

I replaced `jdk.jshell.spi.ExecutionControl.NotImplementedException` with `java.lang.UnsupportedOperationException`.

**Comment by cportele** [comment]
Oops, thanks @azahnen! I thought that the NotImplemented exception was a standard Java exception - obviously, I didn't check the class path.

**Pull request merged**
