### PR TITLE
add module maintenance levels and descriptions

### PR DESCRIPTION
**Pull request by azahnen**
### Pull request checklist

-   [ ] Added/updated unit tests
-   [x] Updated documentation
-   [x] All checks are passing

Depends on interactive-instruments/xtraplatform#157.
Depends on interactive-instruments/xtraplatform-spatial#248.

### CODE REVIEW

**Comment by azahnen** [comment]
Deploying preview to https://interactive-instruments-ldproxy-pr-1130.surge.sh

**Comment by azahnen** [comment]
@cportele 
See https://interactive-instruments-ldproxy-pr-1130.surge.sh/references/modules.html. 
I did not yet deprecate `xtraplatform-features-gml`, I think we should only do that if we really plan to remove the module in the next 1-2 years, otherwise maintenance level `none` should be sufficient.

**Comment by cportele** [comment]
@azahnen - Thanks, I will review, update if I find anything and then merge.

Agreed, we can discuss about `xtraplatform-features-gml` after the release of v4.

**Comment by cportele** [comment]
@azahnen - The DE descriptions are not used in the DE version of the modules page: https://interactive-instruments-ldproxy-pr-1130.surge.sh/de/references/modules.html.

**Review by cportele — APPROVED** [review]
Looks good. We can merge, once the `descriptionDe` is fixed.

**Comment by azahnen** [comment]
@cportele 
The issue is fixed: https://interactive-instruments-ldproxy-pr-1130.surge.sh/de/references/modules.html
I will start to merge.

**Pull request merged**
